name: Test

on:
  pull_request:
  push:
    tags:
      - "**"
    branches:
      - "**"
  workflow_dispatch:

jobs:
  docker:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Test
        run: go test -v ./...
